# models/exam.py

"""
This file can be used to define the structure of an Exam,
any validation logic, or helper functions related to the exam data model.
For a simple MongoDB setup with Flask-PyMongo, we might not need a formal class here,
as data is often handled as dictionaries directly.

However, defining a conceptual structure or validation functions can be useful.

Conceptual Exam Structure:
{
    "_id": ObjectId(),  // Auto-generated by MongoDB
    "exam_id": "string (uuid)", // Our application-specific unique ID
    "kid_id": "string",
    "exam_name": "string",
    "exam_date": "string (ISO YYYY-MM-DD)",
    "subject": "string",
    "marks_obtained_percentage": float,
    "class_top_percentage": float (optional)
}
"""

# Example: A helper function if needed for validation (can be expanded)
# def validate_exam_data(data):
#     required_fields = ["kid_id", "exam_name", "exam_date", "subject", "marks_obtained_percentage"]
#     errors = {}
#     for field in required_fields:
#         if field not in data or not data[field]:
#             errors[field] = f"{field} is required."
#
#     if "marks_obtained_percentage" in data:
#         try:
#             marks = float(data["marks_obtained_percentage"])
#             if not (0 <= marks <= 100):
#                 errors["marks_obtained_percentage"] = "Marks must be between 0 and 100."
#         except ValueError:
#             errors["marks_obtained_percentage"] = "Marks must be a valid number."
#
#     if "class_top_percentage" in data and data["class_top_percentage"] is not None:
#         try:
#             top_marks = float(data["class_top_percentage"])
#             if not (0 <= top_marks <= 100):
#                 errors["class_top_percentage"] = "Class top percentage must be between 0 and 100."
#         except ValueError:
#             errors["class_top_percentage"] = "Class top percentage must be a valid number."
#
#     return errors

# No explicit Exam class needed if we are directly using dicts with PyMongo,
# but if we were using an ODM like MongoEngine, this is where the class would go.
pass
```
