from fastapi import APIRouter, Depends, HTTPException, status, Request
from typing import List, Optional
from models.insight_models import (
    AIInsightCreate, AIInsightResponse, AIInsightUpdate,
    GenerateInsightRequest, AIModelResponse, AIModelInput, AIInsightInDB
)
from crud import insight_crud
from db.mongodb import get_db # Will be used by Depends
from pymongo.database import Database
import uuid
from datetime import datetime, timezone
import requests # For calling other services and AI model
import os
import json

router = APIRouter()

USER_SERVICE_URL = os.getenv("USER_SERVICE_URL", "http://localhost:8080/api/users")
EXAM_SERVICE_URL = os.getenv("EXAM_SERVICE_URL", "http://localhost:5001/api/exams") # kid_id is part of path
COLAB_MODEL_URL = os.getenv("COLAB_MODEL_URL", "http://fake-ai-model.com/generate")
COLAB_API_KEY = os.getenv("COLAB_API_KEY", "fake_api_key")


@router.get("/health", status_code=status.HTTP_200_OK, tags=["Health"])
async def health_check():
    return {"status": "AI Insights Service is running"}


@router.post("/generate/{kid_id}", response_model=AIInsightResponse, status_code=status.HTTP_201_CREATED, tags=["Insights Generation"])
async def generate_and_store_insight(kid_id: str, request: Request, db: Database = Depends(get_db)):
    # 1. Fetch user details
    user_details = None
    try:
        user_response = requests.get(f"{USER_SERVICE_URL}/{kid_id}")
        user_response.raise_for_status() # Raise an exception for HTTP errors
        user_details = user_response.json()
    except requests.exceptions.RequestException as e:
        print(f"Error fetching user details for kid_id {kid_id}: {e}")
        # Depending on requirements, might still proceed or raise error
        # For now, we'll proceed but log it. AI model might handle missing data.
        pass # Or: raise HTTPException(status_code=status.HTTP_503_SERVICE_UNAVAILABLE, detail=f"User service error: {e}")

    # 2. Fetch exam data
    exam_data = None
    try:
        # Note: The Exam Service route is /api/exams/kids/{kid_id}/exams
        # The EXAM_SERVICE_URL is currently http://localhost:5001/api/exams
        # So, the path should be kids/{kid_id}/exams relative to this base.
        exam_response = requests.get(f"{EXAM_SERVICE_URL}/kids/{kid_id}/exams")
        exam_response.raise_for_status()
        exam_data = exam_response.json()
    except requests.exceptions.RequestException as e:
        print(f"Error fetching exam data for kid_id {kid_id}: {e}")
        # Similar handling as user_details
        pass # Or: raise HTTPException(status_code=status.HTTP_503_SERVICE_UNAVAILABLE, detail=f"Exam service error: {e}")

    # 3. Prepare payload for External AI Model
    ai_model_payload = AIModelInput(kid_id=kid_id, user_details=user_details, exam_data=exam_data)

    # 4. Call External AI Model (MOCKED FOR NOW)
    print(f"Calling External AI Model at: {COLAB_MODEL_URL}")
    # In a real scenario:
    # headers = {"Authorization": f"Bearer {COLAB_API_KEY}"}
    # response = requests.post(COLAB_MODEL_URL, json=ai_model_payload.model_dump(), headers=headers)
    # response.raise_for_status()
    # ai_model_output_data = response.json()
    # ai_model_output = AIModelResponse(**ai_model_output_data)

    # MOCK RESPONSE:
    print("USING MOCKED AI MODEL RESPONSE")
    mock_ai_response_data = {
        "progress_analysis": f"Mock progress analysis for {user_details.get('name', 'kid ' + kid_id) if user_details else 'kid ' + kid_id}.",
        "daily_schedule": ["Morning: Math (1hr)", "Afternoon: Reading (30min)", "Evening: Science Project (45min)"],
        "weekly_schedule": ["Mon-Fri: Regular subjects", "Sat: Review week's topics", "Sun: Rest or light activity"],
        "monthly_schedule": ["Week 1-2: Focus on core subjects", "Week 3: Project work", "Week 4: Revision and tests"],
        "suggestions": ["Try visual aids for history.", "Practice coding daily for 15 mins."]
    }
    ai_model_output = AIModelResponse(**mock_ai_response_data)
    
    # 5. Create and Store Insight
    insight_to_create = AIInsightCreate(
        kid_id=kid_id,
        progress_analysis=ai_model_output.progress_analysis,
        daily_schedule=ai_model_output.daily_schedule,
        weekly_schedule=ai_model_output.weekly_schedule,
        monthly_schedule=ai_model_output.monthly_schedule,
        suggestions=ai_model_output.suggestions
        # insight_id and last_updated are auto-generated by Pydantic default_factory
    )
    
    try:
        # create_insight in CRUD now handles replacing existing insight for the kid
        created_insight_db: AIInsightInDB = insight_crud.create_insight(insight_data=insight_to_create)
        if not created_insight_db:
            raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail="Failed to create insight in DB.")
        
        # Convert AIInsightInDB to AIInsightResponse
        return AIInsightResponse(**created_insight_db.model_dump())

    except Exception as e: # Broad exception for DB errors for now
        print(f"Database error while creating insight: {e}")
        raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail=f"Could not save insight: {e}")


@router.get("/kid/{kid_id}", response_model=Optional[AIInsightResponse], tags=["Insights CRUD"])
async def read_insight_for_kid(kid_id: str, db: Database = Depends(get_db)):
    insight = insight_crud.get_insight_by_kid_id(kid_id=kid_id)
    if insight is None:
        # Return 200 with null body or empty object if preferred over 404 for "no insight YET"
        return None 
        # raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="No insight found for this kid")
    return AIInsightResponse(**insight.model_dump())


@router.get("/{insight_id}", response_model=AIInsightResponse, tags=["Insights CRUD"])
async def read_insight(insight_id: str, db: Database = Depends(get_db)):
    insight = insight_crud.get_insight_by_insight_id(insight_id=insight_id)
    if insight is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Insight not found")
    return AIInsightResponse(**insight.model_dump())


@router.put("/{insight_id}", response_model=AIInsightResponse, tags=["Insights CRUD"])
async def update_existing_insight(insight_id: str, insight_update_data: AIInsightUpdate, db: Database = Depends(get_db)):
    updated_insight = insight_crud.update_insight(insight_id=insight_id, insight_data=insight_update_data)
    if updated_insight is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Insight not found to update")
    return AIInsightResponse(**updated_insight.model_dump())


@router.delete("/{insight_id}", status_code=status.HTTP_204_NO_CONTENT, tags=["Insights CRUD"])
async def delete_existing_insight(insight_id: str, db: Database = Depends(get_db)):
    deleted = insight_crud.delete_insight(insight_id=insight_id)
    if not deleted:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Insight not found to delete")
    return None # FastAPI handles 204 No Content response automatically
```
